export const StackNavigator = {
  HOME: 'HOME',
  ANIMATION1_SCREEN: 'ANIMATION1_SCREEN',
  ANIMATION2_SCREEN: 'ANIMATION2_SCREEN',
  SWITCH_SCREEN: 'SWITCH_SCREEN',
  ALERT_SCREEN: 'ALERT_SCREEN',
  TEXTINPUT_SCREEN: 'TEXTINPUT_SCREEN',
  PULL_TO_REFRESH_SCREEN: 'PULL_TO_REFRESH_SCREEN',
  SECTION_LIST_SCREEN: 'SECTION_LIST_SCREEN',
  MODAL_SCREEN: 'MODAL_SCREEN',
  INFINITESCROLL_SCREEN: 'INFINITESCROLL_SCREEN',
};

const Route = {
  ...StackNavigator,
};

export default Route;
export type Routes = keyof typeof Route;
